---
config:
    theme: mc
---
erDiagram
    
    fruit }|..o| supplier : supplied_by
    fruit{
        string type
        string variety
        string season
        string supplier
        int qty
        string qty_measurement

    }